# This rule is not used by the project derived-secret-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to secrets.oleksiyp.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: derived-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: masterpassword-viewer-role
rules:
- apiGroups:
  - secrets.oleksiyp.dev
  resources:
  - masterpasswords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.oleksiyp.dev
  resources:
  - masterpasswords/status
  verbs:
  - get
