apiVersion: secrets.oleksiyp.dev/v1alpha1
kind: MasterPassword
metadata:
  labels:
    app.kubernetes.io/name: derived-secret-operator
    app.kubernetes.io/managed-by: kustomize
    app: test
  name: default
spec:
  # Generate a master password with default length (86 characters)
  # The secret will be created automatically with name "default-mp"
  # in the operator namespace (derived-secret-operator-system)
  length: 86
