apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "derived-secret-operator.fullname" . }}-manager-role
  labels:
    {{- include "derived-secret-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - secrets.oleksiyp.dev
  resources:
  - masterpasswords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.oleksiyp.dev
  resources:
  - masterpasswords/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.oleksiyp.dev
  resources:
  - masterpasswords/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secrets.oleksiyp.dev
  resources:
  - derivedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.oleksiyp.dev
  resources:
  - derivedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.oleksiyp.dev
  resources:
  - derivedsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
