{{- if .Values.defaultMasterPassword.enabled }}
apiVersion: secrets.oleksiyp.dev/v1alpha1
kind: MasterPassword
metadata:
  name: {{ .Values.defaultMasterPassword.name }}
  labels:
    {{- include "derived-secret-operator.labels" . | nindent 4 }}
spec:
  length: {{ .Values.defaultMasterPassword.length }}
  secret:
    name: {{ .Values.defaultMasterPassword.name }}-mp
    create: true
{{- end }}
